### ISSUE TITLE
License Change To AGPL

### ISSUE THREAD

**Issue by KyraD** [michield/phplist#63]
In response to the following, my code would be MIT/WTFPL. Sorry, you emailed me at a forwarding account which has no reply capabilities, so responding here instead under my identity used for commits. =o)

> Hi

> I'm writing to you, because at some point in time you have contributed to the phpList codebase.

> Many thanks

> Michiel

> -- 

> Michiel Dethmers
> http://www.phplist.com
> Open Source newsletter manager

**Comment by michield** [comment]
That's great, thanks.
