### ISSUE TITLE
Incorrect URL for unsubscribe link

### ISSUE THREAD

**Issue by moshekaplan** [michield/phplist#65]
When visiting  the subscribe page (`?p=subscribe&id=1`), even if the `$pageroot` variable is updated, the unsubscribe link still points to `/lists/?p=unsubscribe&id=1`

**Comment by moshekaplan** [comment]
This issue can be replicated by adding an `echo getConfig("unsubscribeurl");` after `require_once dirname(__FILE__)."/admin/defaultconfig.php";` on line 49 (https://github.com/michield/phplist/blob/master/public_html/lists/index.php#L49).

**Comment by michield** [comment]
That is probably because the unsubscribe URL is already saved in the DB.

What if you edit the value in the settings ? Is it still using /lists/ ?

**Comment by moshekaplan** [comment]
You're correct, the value in settings is `http://[WEBSITE]/lists/?p=unsubscribe`.
If I update that value, it works without issue. It would be nice if it did a similar replace for pageroot as it does for [WEBSITE], so it doesn't need to be manually edited if the pageroot changes.

**Comment by michield** [comment]
True. But in the end, the pageroot is not expected to change.
